device-id: <iotedge-device-id>
hub_endpoint: <iothub-builtin-endpoint>

service_principal:
  username_secret: <sp-user>
  password: <sp-pass>
  tenant_secret: <tenant>


send_telemetry:
  image_version: <version-tag>
  module_version: <module-tag>
  build_path: <path-of-dockerfile>

temp_model:
  image_version: <version-tag>
  module_version: <module-tag>
  build_path: <path-of-dockerfile>

acr:
  server: <acr-server-url>
  username_secret: <acr-username>
  password: <acr-password>

deployment:
  input_template: <path-of-template>
  output_deployment: <path-of-deployment>


